isport_foxhun/isport_foxhun/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using isport_foxhun.Models;
using Microsoft.ApplicationBlocks.Data;
using System.Configuration;
namespace isport_foxhun.Controllers
{
    [LoginExpireAttribute]
    public class PlayerController : Controller
    {
        // new player
        public ActionResult Parameter(string position)
        {
            PlayerViewModel model = new PlayerViewModel();

            model = GetParameterByPosition(model,position);

            return PartialView(model);
        }

        public ActionResult ParameterSum(string position)
        {
            PlayerViewModel model = new PlayerViewModel();

            model = GetParameterByPosition(model, position);

            return PartialView(model);
        }

        public ActionResult ParameterSum1(PlayerViewModel model)
        {
            return PartialView("ParameterSum", model);
        }

        // update player
        public ActionResult Parameter1(PlayerViewModel model)
        {

            return PartialView("parameter", model);
        }

        public ActionResult insert()
        {

            return PartialView();
        }

        private PlayerViewModel GetParameterByPosition(PlayerViewModel model ,string position)
        {
            string[] strs = new string[6];

            try
            {


                #region get Config
                if (position == "CB" || position == "LB" || position == "FB" || position == "LWB" || position == "RWB" || position == "DM")
                {
                    strs[0] = "ControlNameCBTH";
                    strs[1] = "AttackNameCBTH";
                    strs[2] = "DefenseNameCBTH";
                    strs[3] = "TacktickNameCBTH";
                    strs[4] = "PhysicalNameCBTH";
                    strs[5] = "MentalNameCBTH";
                }
                else if (position == "CM" || position == "AM")
                {
                    strs[0] = "ControlNameCMTH";
                    strs[1] = "AttackNameCMTH";
                    strs[2] = "DefenseNameCMTH";
                    strs[3] = "TacktickNameCMTH";
                    strs[4] = "PhysicalNameCMTH";
                    strs[5] = "MentalNameCMTH";
                }
                else if (position == "LW" || position == "RW")
                {
                    strs[0] = "ControlNameWTH";
                    strs[1] = "AttackNameWTH";
                    strs[2] = "DefenseNameWTH";
                    strs[3] = "TacktickNameWTH";
                    strs[4] = "PhysicalNameWTH";
                    strs[5] = "MentalNameWTH";
                }
                else if (position == "CF" || position == "WF" || position == "ST")
                {
                    strs[0] = "ControlNameSTTH";
                    strs[1] = "AttackNameSTTH";
                    strs[2] = "DefenseNameSTTH";
                    strs[3] = "TacktickNameSTTH";
                    strs[4] = "PhysicalNameSTTH";
                    strs[5] = "MentalNameSTTH";
                }
                else if (position == "GK")
                {
                    strs[0] = "ControlNameGKTH";
                    strs[1] = "AttackNameGKTH";
                    strs[2] = "DefenseNameGKTH";
                    strs[3] = "TacktickNameGKTH";
                    strs[4] = "PhysicalNameGKTH";
                    strs[5] = "MentalNameGKTH";
                }
                #endregion

                ParameterViewModel pModel;
                List<ParameterViewModel> pModels;
                string[] paramValue = new string[] { };
                int index = 0;
                for (int i = 0; i < strs.Length; i++)
                {
                    pModels = new List<ParameterViewModel>();
                    if (model.player != null)
                    {
                        switch (i)
                        {
                            case 0: paramValue = model.player.control.Split(','); break;
                            case 1: paramValue = model.player.attack.Split(','); break;
                            case 2: paramValue = model.player.defense.Split(','); break;
                            case 3: paramValue = model.player.tacktick.Split(','); break;
                            case 4: paramValue = model.player.physical.Split(','); break;
                            case 5: paramValue = model.player.mental.Split(','); break;
                        }
                    }
                    index = 0;
                    foreach (string s in ConfigurationManager.AppSettings[strs[i]].Split(','))
                    {
                        pModel = new ParameterViewModel();
                        pModel.name = s;
                        try
                        {
                            pModel.value = (paramValue.Length >= index && paramValue[index] != "") ? int.Parse(paramValue[index]) : 0;
                        }
                        catch { pModel.value = 0; }
                        pModels.Add(pModel);
                        index++;
                    }
                    switch (i)
                    {
                        case 0: model.Control = pModels; break;
                        case 1: model.Attack = pModels; break;
                        case 2: model.Defense = pModels; break;
                        case 3: model.Tacktick = pModels; break;
                        case 4: model.Physical = pModels; break;
                        case 5: model.Mental = pModels; break;
                    }

                }
            }
            catch
            { }
            return model;
        }

        public ActionResult History(string player_id)
        {
            PlayerHistoryViewModel pModel = new PlayerHistoryViewModel();
            pModel.playerHistory = new AppCodeModel().GetPlayerHistoryById(player_id);

            return PartialView(pModel);
        }
        // GET: Player
        public ActionResult Index(string team_id,string id) // id is team id
        {
            PlayerViewModel model = new PlayerViewModel();
            foxhun_player player = new foxhun_player();
            model.player = player;
            if (id != null && id != "")
            {

                List<foxhun_player> pList = new AppCodeModel().GetPlayerById(id);

                if (pList.Count > 0)
                {
                    model.player = pList[0];

                    model = GetParameterByPosition(model, model.player.position);
                }
                
            }
            else new RedirectResult("~/Home/Index");

            return View(model);
        }

        public ActionResult newplayer(string team_id)
        {
            ViewBag.team_id = team_id;
            List<foxhun_team> team = new TeamModels().GetTeamById(team_id);
            PlayerViewModel model = new PlayerViewModel();
            foxhun_player player = new foxhun_player();
            model.player = player;
            if (team.Count > 0)
            {
                ViewBag.region = team[0].region;
                ViewBag.team = team[0].name;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult insertplayer(PlayerViewModel model, HttpPostedFileBase image) // insert player for team
        {
            try
            {
                HttpPostedFileBase file = image;
                if (file != null && file.ContentLength > 0)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = Server.MapPath("~/images/") + pic;

                    file.SaveAs(path);
                    // Update data model
                    model.player.image = "~/images/" + pic;
                }

                //string[] txtParam = new string[] { "ctr_", "att_", "def_", "tac_", "phy_", "men_" };
                model.player.team_id = model.player.team_id;
                model.player.datetime = DateTime.Now;
                model.player.sum = 0;
                model.player.control = "0";
                model.player.attack = "0";
                model.player.defense = "0";
                model.player.tacktick = "0";
                model.player.physical = "0";
                model.player.mental = "0";



                model.player.id = Guid.NewGuid().ToString();
                AppCodeModel.InsertPlayer(model);


                return RedirectToAction("Index", "Team", new { id = model.player.team_id });//View("~/team/index.cshtml", null, new { id = Request["team_id"] });
                                                                                            //return PartialView("~/views/player/insert.cshtml", null);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("newplayer","player",new {team_id= model.player.team_id });
            }
        }


        [HttpPost]
        public ActionResult AddPlayer(PlayerViewModel model, HttpPostedFileBase image)
        {
            HttpPostedFileBase file = image;
            if( file != null && file.ContentLength > 0 )
            {
                string pic = System.IO.Path.GetFileName(file.FileName);
                string path = Server.MapPath("~/images/")+ pic;

                file.SaveAs(path);
                // Update data model
                model.player.image= "~/images/"+pic;
            }

            string[] txtParam = new string[] {"ctr_","att_","def_","tac_","phy_","men_" };
            model.player.team_id = (Request["team"] != null && Request["team"] != "") ?Request["team"]:"";
            model.player.sum = 0;
            for (int i =0;i<txtParam.Length;i++)
            {
                for(int index=0;index<10;index++)
                {

isport_foxhun/isport_foxhun/Controllers/ScoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using isport_foxhun.Models;
namespace isport_foxhun.Controllers
{
    [LoginExpireAttribute]
    public class ScoutController : Controller
    {
        // GET: Scout
        public ActionResult Index(string match_id)
        {
            ViewBag.match_id = match_id;
            ScoutViewListModels model = new ScoutViewListModels();
            model.list = new ScoutModels().GetScoutByMatchId(match_id);
            List<MatchViewModels> mModel = new MatchModels().GetMatchById(match_id);
            if( mModel.Count > 0 )
            {
                ViewBag.TeamCode1 = mModel[0].team_code1;
                ViewBag.TeamCode2 = mModel[0].team_code2;
            }
            return View(model);
        }

        public ActionResult PlayerDetail(PlayerViewModelList model)
        {
            //PlayerViewModelList pList = new Models.PlayerViewModelList();
            //pList.playerList = new AppCodeModel().GetPlayerAll(txtSearch);
            return PartialView(model);
        }

        public ActionResult player(string player_id)
        {
            PlayerViewModelList model = new PlayerViewModelList();
            model.playerList = new AppCodeModel().GetPlayerById(player_id);
            return PartialView(model);
        }

        public ActionResult playertoscout(PlayerViewModelList model)
        {
            return PartialView(model);
        }
        public ActionResult ListPlayer(string txtSearch)
        {
            PlayerViewModelList pList = new Models.PlayerViewModelList();
            pList.playerList = new AppCodeModel().GetPlayerAll(txtSearch);
            pList.listScout = new ScoutModels().GetScoutByScoutId(commom.AppUtils.Session.User.id);
            return View(pList);
        }

        [HttpPost]
        public ActionResult insertplayer()
        {
            string matchId = Request.Form["item.match_id"];
            for (int i = 1; i < 3; i++)
            {
                string[] playerId = Request.Form["infoPlayer_team" + i.ToString()] != null ? Request.Form["infoPlayer_team" + i.ToString()].Split(',') : null;
                if ( playerId != null && playerId.Length > 0)
                {
                    foreach (string p in playerId)
                    {
                        // insert scout
                        MatchModels.insertScout(matchId, commom.AppUtils.Session.User.id, p, Request.Form["team"+i.ToString()], "blue");
                    }

                }
            }
            return RedirectToAction("index", "scout", new { match_id = matchId });
        }
    }
}

isport_foxhun/isport_foxhun/Views/Scout/PlayerDetail.cshtml
@model isport_foxhun.Models.PlayerViewModelList


<div class="row">
    @foreach (var list in Model.playerList)
    {
        <div class="col-md-4">
            <div class="thumbnail">
                <div class="caption" style="min-height:320px;">
                    <div class="row">
                        <div class="col-md-8">
                            <p>No. @list.seq</p>
                            <p>Position : @list.position</p>
                            
                        </div>
                        <div class="col-md-4">
                            @{ if (list.image != null)
                                {
                                    <img src="@Url.Content(list.image)" class="img-thumbnail" style="max-height:150px;min-height:150px;" />
                                }
                                else
                                {
                                    <img src="~/images/isport.png" class="img-thumbnail" style="max-height:150px;min-height:150px;" />
                                }
                            }
                        </div>
                    </div>
                    <div class="row" style="margin:10px;">
                        <p>@list.name</p>
                        <p>Age :@list.age wigth :@list.wight hight :@list.hight</p>
                        <p class="small">Team : @list.team</p>
                        <!--

                        <div class="progress">
                            {
                                var i = list.tacking * 10;
                                var itxt = i.ToString() + '%';

                                <div class="progress-bar" role="progressbar" aria-valuenow=list.tacking aria-valuemin="0" aria-valuemax="10" style="width: itxt">
                                    Tacking : list.tacking.ToString()
                                </div>
                            }
                        </div>
                            -->

                    </div>
                    <h6>Detail :</h6>
                    <p class="small">
                        @list.detail
                    </p>
                    <p><a class="btn btn-primary" id="btnPlayerDetail" onclick="GetCompare('@list.id');" >Keep detail&raquo;</a></p> <!-- href="~/player/index?id=list.id" -->

                </div>
            </div>

        </div>
                                }
</div>

isport_foxhun/isport_foxhun/Views/Scout/index.cshtml
@model isport_foxhun.Models.ScoutViewListModels
@{
    ViewBag.Title = "index";
    int index = 1;
}

@using (Html.BeginForm("insertplayer", "Scout", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{

<div class="container">
    
    @foreach (var item in Model.list)
    {
        if (index == 1)
        {
            @Html.HiddenFor( m=> item.match_id, new { @Value = ViewBag.match_id })

            <div class="row">
                <div class="col-md-12">
                    <h3> @item.match</h3>
                </div>
            </div>
            <h3> player to scout</h3>
            <hr />
        }

        
        <div class="col-md-4 col-sm-4">
            <div class="thumbnail" style="min-height:300px;">
                <div class="caption">
                    <div class="row">
                        <div class="col-md-8 col-sm-8">
                            <p>No. : @item.seq</p>
                            <p>Name : @item.player</p>
                            <p>Position : @item.player_position</p>
                            

                        </div>
                        <div class="col-md-4">
                            @if (item.player_image != null && item.player_image != "")
                            {
                                <img src="@Url.Content(item.player_image)" class="img-thumbnail" style="max-height:150px;min-height:90px;" />
                            }
                            else
                            {
                                <img src="~/images/KING_POWER_CUP_LOGO_B.jpg" class="img-thumbnail" style="max-height:150px;min-height:90px;" />
                            }
                        
                        
                        </div><br/>
                        <p><a class="btn btn-primary" target="_blank" href="~/player/index?id=@item.player_id">more detail&raquo;</a></p>
                    </div>
                    <div class="row">
                        <p class="small">Team : @item.team</p>
                        <p class="small">Detail : @item.detail</p>
                    </div>
                </div>
            </div>
        </div>

        index++;
    }

</div>
<hr>
<h3> other player</h3>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            @Html.Action("viewplayerbyteam", "Match", new { team_id = ViewBag.TeamCode1, team = "team1" })
        </div>
        <div class="col-md-6 panel-info">
            @Html.Action("viewplayerbyteam", "Match", new { team_id = ViewBag.TeamCode2, team = "team2" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <input id="btnSubmit" type="submit" class="btn btn-primary btn-lg center-block" value="Add Player" />
        </div>
    </div>
</div>

}

isport_foxhun/isport_foxhun/Views/Scout/listplayer.cshtml
@model isport_foxhun.Models.PlayerViewModelList

@{
    ViewBag.Title = "listplayer";
    int index = 1;
}

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>



<script>


    $(document).ready(function () {
        var compare1 = "";

        $(function () {
            $("#tabs").tabs();
        });

    });

    function GetCompare(id) {
        $.ajax({
            type: "GET",
            url: "/player/compareplayer",
            data: { id: id }
        }).done(function (htmlResponse) {
            //console.log(index);

            if ($("#lblCompare").val() == "") {
                compare1 = "false";
                $("#compare1").html(htmlResponse)
                $("#lblCompare").val("false");
                alert("keep success");
            } else {
                $("#compare2").html(htmlResponse)
                alert("keep success");
            }
            @{
                index++;
            }
        });
    }


</script>

<h2>List Player</h2>

<input id="lblCompare" type="hidden" value="" />
<div class="row" style="margin-left:20px;">

    <div class="col-md-6"></div>

    @using (Ajax.BeginForm("listplayer", "scout", new AjaxOptions { UpdateTargetId = "grid_list", HttpMethod = "POST" }))
    {
        <div class="col-md-6">
            <div class="input-group">
                <input type="text" id="txtSearch" name="txtSearch" class="form-control pull-right" placeholder="Search for name or position">
                <div class="input-group-btn">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    <button class="btn btn-default">Search</button>
                </div>
            </div>
        </div>
    }


</div>
<hr />
<div id="tabs">
    <ul>
        <li><a href="#tabs-1">player to scout</a></li>
        <li><a href="#tabs-2">List Player</a></li>
        <li><a href="#tabs-3">Compare Player</a></li>
        
    </ul>
    <div id="tabs-1">
        <div>
            <div id="playertoscout" class="row">
                @Html.Action("playertoscout", "scout", Model)
            </div>
        </div>
    </div>
    <div id="tabs-2">
        <div>
            <div id="grid_list" class="row">

                @Html.Action("PlayerDetail", "scout", Model)

            </div>

        </div>
    </div>
    <div id="tabs-3">
        <div class="row">
            <div id="compare1" class="col-md-6" style="width:50%;max-width:50%;"></div>
            <div id="compare2" class="col-md-6" style="width:50%;max-width:50%;"></div>
        </div>
    </div>
</div>
        
     
        

isport_foxhun/isport_foxhun/Views/Scout/player.cshtml
@model isport_foxhun.Models.PlayerViewModelList
@{
    Layout = null;
}



@foreach (var list in Model.playerList)
{

    <div class="col-md-6">
        <div class="row">
            <div class="col-md-8">
                <p>Position : @list.position</p>
                <p>Age :@list.age wigth :@list.wight hight :@list.hight</p>
            </div>
            <div class="col-md-4">
                @{ if (list.image != null)
                    {
                        <img src="@Url.Content(list.image)" class="img-thumbnail" style="max-height:150px;" />
                    }
                    else
                    {
                        <img src="~/images/isport.png" class="img-thumbnail" style="max-height:150px;" />
                    }
                }
            </div>
        </div>
        <div class="row" style="margin:10px;">
        </div>
        <h6>Detail :</h6>
        <p>
            @list.detail
        </p>
        <p><a class="btn btn-primary" target="_blank" href="~/player/index?id=@list.id">more detail&raquo;</a></p> 
    </div>
                    }

isport_foxhun/isport_foxhun/Views/Scout/playertoscout.cshtml
@model isport_foxhun.Models.PlayerViewModelList

<div class="=row">
    @foreach (var lScout in Model.listScout)
            {
        <div class="col-md-4 col-sm-4 ">
            <div class="thumbnail" style="min-height:300px;">
                <div class="caption">
                    <div class="row">
                        <div class="col-md-8">
                            <p>No. : @lScout.seq</p>
                            <p>Position : @lScout.player_position</p>
                        </div>
                        <div class="col-md-4 col-sm-4">
                            @if (lScout.player_image != null && lScout.player_image != "")
                            {
                                <img src="@Url.Content(lScout.player_image)" class="img-thumbnail" style="max-height:150px;min-height:90px;" />
                            }
                            else
                            {
                                <img src="~/images/KING_POWER_CUP_LOGO_B.jpg" class="img-thumbnail" style="max-height:150px;min-height:90px;" />
                            }


                        </div><br />
                        <p><a class="btn btn-primary" target="_blank" href="~/player/index?id=@lScout.player_id">more detail&raquo;</a></p>
                    </div>
                    <div class="row">
                        <p>Name : @lScout.player</p>                        
                        <p class="small">Team : @lScout.team</p>
                        <p class="small">Detail : 
                        @if (lScout.detail != null && lScout.detail.Length > 50)
                        {
                            @lScout.detail.Substring(0, 50)
                        }
                        else
                        {
                            @lScout.detail
                        }
                        </p>
                    </div>
                </div>
            </div>
        </div>
    }
</div>